style(breakpoints): reduce layout to 2 breakpoints
proveuswrong/webapp-tp pull request #238
Opened 2023-07-06 17:50 UTC by gratestas

fix #236

2023-07-07 13:04 UTC, 0xferit requested changes

2023-07-07 13:10 UTC, gratestas commented on src/stylesheets/variables/_breakpoints.scss
> +$navbar: 780px;
The nav pushes the connect buttons out of the parent div due to the  length of the navLink's when the viewport falls in between 600px and ~780px

2023-07-07 13:37 UTC, 0xferit commented on src/stylesheets/variables/_breakpoints.scss
> +$navbar: 780px;
What about using 1200 instead?

2023-07-10 10:21 UTC, gratestas commented on src/stylesheets/variables/_breakpoints.scss
> +$navbar: 780px;
yeah, also possible.

2023-07-11 11:12 UTC, 0xferit approved these changes

2023-07-11 11:19 UTC, merged